version: "3"

services:
  api:
    container_name: api
    build: ./
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/server

  db:
    image: mysql/mysql-server:5.7.28
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d