version: "3"

services:
  api:
    container_name: api
    build: ./docker/api
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/server

  db:
    image: mysql:5.7
    container_name: db
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
